spring:
  application:
    name: eurka-server

server:
  port: 8761
  hostname: 127.0.0.1


eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${server.hostname}:${server.port}/eureka/

